unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind -n M-H previous-window
bind -n M-L next-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set-option -g default-command $SHELL
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 100000

setw -g mode-keys vi

bind Escape copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
bind -T copy-mode-vi Escape send-keys -X cancel

bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind r source-file ~/.tmux.conf \; display "tmux config reloaded"

set -g status-interval 60
set -g status-left-length 100
set -g status-right-length 100
set -g status-justify left

set -g message-style "fg=#88C0D0,bg=#3B4252"
set -g message-command-style "fg=#88C0D0,bg=#3B4252"

set -g pane-border-style "fg=#4C566A"
set -g pane-active-border-style "fg=#88C0D0"

set -g status-style "fg=#D8DEE9,bg=#2E3440"

set -g status-left "#[fg=#2E3440,bg=#88C0D0,bold] #S "
set -g status-right "#[fg=#4C566A] %Y-%m-%d %H:%M "

setw -g window-status-activity-style "fg=#D8DEE9,bg=#3B4252"
setw -g window-status-separator ""
setw -g window-status-style "fg=#4C566A,bg=#2E3440"
setw -g window-status-format "#[fg=#2E3440,bg=#2E3440]#[fg=#4C566A] #I #W #[fg=#2E3440,bg=#2E3440]"
setw -g window-status-current-format "#[fg=#3B4252,bg=#3B4252]#[fg=#88C0D0,bold] #I #W #[fg=#3B4252,bg=#2E3440]"

run '~/.tmux/plugins/tpm/tpm'
