unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind -n M-H previous-window
bind -n M-L next-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set-option -g default-command $SHELL
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 100000

setw -g mode-keys vi

bind Escape copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
bind -T copy-mode-vi Escape send-keys -X cancel

bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind r source-file ~/.tmux.conf \; display "tmux config reloaded"

set -g status-interval 60
set -g status-left-length 100
set -g status-right-length 100
set -g status-justify left

set -g message-style "fg=#cba6f7,bg=#45475a"
set -g message-command-style "fg=#cba6f7,bg=#45475a"

set -g pane-border-style "fg=#585b70"
set -g pane-active-border-style "fg=#cba6f7"

set -g status-style "fg=#cdd6f4,bg=#1e1e2e"

set -g status-left "#[fg=#1e1e2e,bg=#cba6f7,bold] #S "
set -g status-right "#[fg=#585b70] %Y-%m-%d %H:%M "

setw -g window-status-activity-style "fg=#cdd6f4,bg=#45475a"
setw -g window-status-separator ""
setw -g window-status-style "fg=#585b70,bg=#1e1e2e"
setw -g window-status-format "#[fg=#1e1e2e,bg=#1e1e2e]#[fg=#585b70] #I #W #[fg=#1e1e2e,bg=#1e1e2e]"
setw -g window-status-current-format "#[fg=#45475a,bg=#45475a]#[fg=#cba6f7,bold] #I #W #[fg=#45475a,bg=#1e1e2e]"

run '~/.tmux/plugins/tpm/tpm'
