# Gleam Light for Kitty
# Inspired by Gleam editor themes and light polar aesthetic

foreground            #2b2f38
background            #f7fbff
cursor                #2b2f38

color0                #f7fbff
color1                #d95468
color2                #5abf91
color3                #e5b76b
color4                #5fa8ff
color5                #ac79b9
color6                #76cddb
color7                #2b2f38

color8                #dce4ea
color9                #e37b8b
color10               #7edaa0
color11               #ecd09b
color12               #89aefe
color13               #b698d4
color14               #91dbe4
color15               #1e2128

selection_foreground  #f7fbff
selection_background  #5fa8ff

