# Catppuccin Mocha Theme for Polybar

[colors]
background = #1e1e2e
foreground = #cdd6f4

black      = #45475a
red        = #f38ba8
green      = #a6e3a1
yellow     = #f9e2af
blue       = #89b4fa
magenta    = #cba6f7
cyan       = #94e2d5
white      = #bac2de

lightblack = #585b70

[colors-light]
background = #cdd6f4
foreground = #1e1e2e

black      = #1e1e2e
red        = #f38ba8
green      = #a6e3a1
yellow     = #f9e2af
blue       = #89b4fa
magenta    = #cba6f7
cyan       = #94e2d5
white      = #cdd6f4

lightblack = #585b70
