[FileDialog]
history=file:///srv/Kaer/music, file:///srv/Kaer, file:///srv/Kaer/Calibre Library, file:///home/hawk0120/Downloads, file:///home/hawk0120/dev/typescript
lastVisited=file:///home/hawk0120/dev/typescript
qtVersion=6.8.2
shortcuts=file:, file:///home/hawk0120
sidebarWidth=87
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0)"
viewMode=Detail
