[qt]
GUIEffects=none
KDE\contrast=4
KWinPalette\activeBackground=#475057
KWinPalette\activeBlend=#fcfcfc
KWinPalette\activeForeground=#fcfcfc
KWinPalette\activeTitleBtnBg=#eff0f1
KWinPalette\frame=#eff0f1
KWinPalette\inactiveBackground=#eff0f1
KWinPalette\inactiveBlend=#4b4743
KWinPalette\inactiveForeground=#bdc3c7
KWinPalette\inactiveFrame=#eff0f1
KWinPalette\inactiveTitleBtnBg=#eff0f1
Palette\active=#000000, #eff0f1, #ffffff, #f6f7f7, #888e93, #c4c8cc, #000000, #ffffff, #000000, #fcfcfc, #eff0f1, #474a4c, #0f56d9, #fcfcfc, #2980b9, #7f8c8d, #eff0f1, #000000, #232627, #fcfcfc, #7f8c8d, #0f56d9
Palette\disabled=#949595, #e3e5e7, #ffffff, #ebedee, #82878c, #bbc0c5, #9c9c9c, #ffffff, #949595, #f0f0f0, #e3e5e7, #474a4c, #e3e5e7, #949595, #a2c8e0, #c7cbcb, #e3e5e7, #000000, #232627, #fcfcfc, #c7cbcb, #e3e5e7
Palette\inactive=#000000, #eff0f1, #ffffff, #f6f7f7, #888e93, #c4c8cc, #000000, #ffffff, #000000, #fcfcfc, #eff0f1, #474a4c, #bdcaf3, #000000, #2980b9, #7f8c8d, #eff0f1, #000000, #232627, #fcfcfc, #7f8c8d, #bdcaf3
font="Noto Sans,10,-1,0,400,0,0,0,0,0,0,0,0,0,0,1"
